services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - /mnt/c/Users/Raghu/Desktop/vachu_files/project/FSDProject/client:/app/client

    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
